### PR TITLE
activity-module

### PR DESCRIPTION
**Pull request by brandonschabell**
Fixed Manifest file issue.

### CODE REVIEW

**Comment by avaidyam** [comment]
This PR is not needed, just rebase from master.

**Comment by brandonschabell** [comment]
This was the second PR... I had many changes that needed to be committed.

**Comment by brandonschabell** [comment]
Scratch that, I didn't see you merged the other one.

**Comment by avaidyam** [comment]
But I see nothing.

**Comment by avaidyam** [comment]
Brando pls

**Pull request closed without merging**
