### PR TITLE
Sleep sounds

### PR DESCRIPTION
**Pull request by avaidyam**
See #38.

### CODE REVIEW

**Comment by avaidyam** [comment]
@Wall-Dough @colinrford @Brahmancer @brandonschabell @MrJohnson **Please verify.**

**Comment by colinrford** [comment]
Seems ok

**Comment by Brahmancer** [comment]
I give it the green light for me.

**Comment by Wall-Dough** [comment]
Can you turn down the volume yet? :smirk:

**Comment by avaidyam** [comment]
We need a UI for that. Sprint 2!

**Pull request merged**
