### PR TITLE
Sensor Context

### PR DESCRIPTION
**Pull request by avaidyam**
See #53.

### CODE REVIEW

**Comment by avaidyam** [comment]
@Wall-Dough @colinrford @Brahmancer @brandonschabell @MrJohnson **Please verify.**

**Comment by Brahmancer** [comment]
Could you discuss how we would use this during our meeting(s)? Apart from that, it seems like you know what you're doing. :shipit: 
Edit: a word

**Comment by Wall-Dough** [comment]
Yeah, I think if you describe it in the meetings we could maybe, _maybe_ provide some insight.

**Comment by avaidyam** [comment]
@Wall-Dough @Brahmancer Works identically to the existing `SensorManager` -- however, this is tied into the ViewModel mechanism; this is the `sensorContext()`. It also broadcasts as events for everyone, so it's technically a singleton but not really because in reality it's a magical unicorn. :8ball:

**Pull request merged**
