### PR TITLE
Updating Annotations

### PR DESCRIPTION
**Pull request by colinrford**
This (build.gradle: line 68: "...23.1.1") was not allowing gradle to build on my machine in the master branch, so I decided to make a new branch, fix it, and make a PR rather than commit straight to master. I also did this just in case I’m just a moron or something.

### CODE REVIEW

**Comment by colinrford** [comment]
**Please, check to see if the current master branch builds and runs for you in IntelliJ or Android Studio as well as on your android device.** If it does, fantastic! If it doesn't, damn! Either way, let everyone know **here**. 

Furthermore, **please check to see if this branch, fix_master_grade, builds and runs for you in your IDE as well as on your android device.** Again, please let everyone know **here** if that works or not. I'm requesting this of all of you ( @avaidyam @Wall-Dough @Brahmancer @brandonschabell @MrJohnson ) because it should take no more than 2-3 minutes altogether.

**Comment by avaidyam** [comment]
Works for me!

**Comment by colinrford** [comment]
the current master branch does?

**Comment by avaidyam** [comment]
Yes! Go to _Android SDK Manager_ and make sure _Android Support Library_ (rev 23.2) and _Android Support Repository_ (rev 26) are updated. 

**This PR will be merged. Anyone who hasn't been following through with this discussion will be left in the cold and ark abyss of Gradle Sync errors. No sympathy shall be given.**

**Comment by colinrford** [comment]
Both of those were good for me! I'm curious why I had issues?

**Comment by avaidyam** [comment]
Gradle referenced an older repository version.

**Pull request merged**
