### PR TITLE
Initial ViewModel support.

### PR DESCRIPTION
**Pull request by avaidyam**
There's a few things this branch accomplishes:
- Support `Observable`s for Android's Data Binding library within the `Module`.
- Initial `ViewContext` interface which details everything the `Module` needs to know.
- `Module` registration support (which needs `init()`, etc... lifecycle).
- `AnimationUtils` for later (not sure why I put it here).
- A REALLY POWERFUL `Dispatcher` class for multithreading madness. (More on this later.)
- Added all of our emails to the TravisCI notifications.

A few things still need to be worked out later:
- Abstract `init()` and `deinit()` functions to mark when the `Module` is born and dying.

See #45.

### CODE REVIEW

**Comment by Brahmancer** [comment]
Looks good! I started a wiki page that talks about viewContext implemented here so at some point, I'd look at that and see if that's correct with what's here.

**Comment by avaidyam** [comment]
I think I totally forgot to actually implement the `ContextBinder` which would do the job of taking the `viewContext` or `dataContext` and shoving it down the `Module`'s throat... Oops. I'll do that after this PR is merged.

**Comment by Brahmancer** [comment]
Out of curiosity, how long does that take?

**Comment by avaidyam** [comment]
That's a good question, Daniel. :cry: 

It might be easy, but I can't really forecast this one since I've never uh, written a runtime dependency injector...

**Comment by Brahmancer** [comment]
so this ContextBinder could be something that everybody gets and have fields called data and view contexts and return them much like how the BaseApplication returns it's context. Does that make sense? Or did you already think of that? :grin:

**Comment by avaidyam** [comment]
Even better, I think it would be as simple as doing:

``` java
Module.requestService(ContextBinder.DATA);
Module.requestService(ContextBinder.VIEW);
```

Then, `Module` would go tell the `ContextBinder` to plug that in and make sure it's unplugged when it's required. It's similar to what you said; in fact, go look at how `Context.getSystemService(...)` is implemented!

**Comment by Brahmancer** [comment]
So would DATA and VIEW be the dataContext object and viewContext objects respectively?

**Comment by avaidyam** [comment]
No, they're just `Strings` that identify the service the `SleepModule` might want:
- `SleepModule` invokes --> `Module.requestService(ContextBinder.DATA);`
- `Module` invokes --> `ContextBinder.doTheThing(theModule, ContextBinder.DATA);`
- `ContextBinder` does the thing
- `SleepModule` now can access `this.dataContext()` without exploding! :+1:

**Pull request merged**
