### PR TITLE
Steps

### PR DESCRIPTION
**Pull request by Brahmancer**
Putting Steps in before Sprint 1 meeting.

### CODE REVIEW

**Comment by colinrford** [comment]
Give me a heads up before this is closed please!

**Comment by colinrford** [comment]
Please do not merge yet I have been working in this branch

**Comment by Brahmancer** [comment]
All I've done so far is just pull from master after #64. Let me know when you're ready.

**Comment by avaidyam** [comment]
Auto-merged; no code review.

**Pull request merged**
